import type { Appearance } from "./core"

/**
 * Finished looks to start from, and the proof that the catalogue can produce
 * clearly different people. Plain data: each is a normal saved appearance.
 */
export const PRESETS: { id: string; name: string; appearance: Appearance }[] = [
  {
    id: "noble",
    name: "Elegant noble",
    appearance: {
      version: 1,
      skin: "#f3c9a8",
      hair: "#e2c07a",
      eyes: "#2f6fb0",
      parts: {
        body: { id: "body_slim" },
        ears: { id: "ears_elf" },
        face: { id: "face_soft" },
        markings: { id: "markings_beauty_mark" },
        eyes: { id: "eyes_soft" },
        eyebrows: { id: "brows_elegant" },
        mouth: { id: "mouth_smile" },
        hair: { id: "hair_cascade" },
        dress: { id: "dress_royal", colors: { primary: "#1f2f6b", secondary: "#f2efe8", trim: "#d4af37" } },
        earrings: { id: "earrings_drops", colors: { primary: "#d4af37", secondary: "#3f6fd1" } },
        necklace: { id: "necklace_pendant", colors: { primary: "#d4af37", secondary: "#3f6fd1" } },
        bracelets: { id: "bracelets_cuffs" },
        hat: { id: "hat_crown", colors: { primary: "#d4af37", secondary: "#3f6fd1" } },
      },
    },
  },
  {
    id: "dark_knight",
    name: "Dark fantasy",
    appearance: {
      version: 1,
      skin: "#e6e9f2",
      hair: "#17141c",
      eyes: "#b0243a",
      parts: {
        body: { id: "body_average" },
        ears: { id: "ears_human" },
        face: { id: "face_sharp" },
        markings: { id: "markings_shadowed" },
        eyes: { id: "eyes_piercing" },
        eyebrows: { id: "brows_furrowed" },
        mouth: { id: "mouth_pout" },
        hair: { id: "hair_wolf" },
        top: { id: "top_shirt", colors: { primary: "#16141c", secondary: "#c9ccd6" } },
        bottom: { id: "bottom_trousers", colors: { primary: "#16141c", secondary: "#8f1d2c" } },
        coat: { id: "coat_cloak", colors: { primary: "#16141c", secondary: "#8f1d2c", trim: "#c9ccd6" } },
        shoes: { id: "shoes_tall", colors: { primary: "#2f3440", secondary: "#16141c", trim: "#c9ccd6" } },
        necklace: { id: "necklace_choker", colors: { primary: "#16141c", secondary: "#8f1d2c" } },
        earrings: { id: "earrings_hoops", colors: { primary: "#c9ccd6" } },
        weapon: { id: "weapon_longsword" },
        horns: { id: "horns_demon" },
      },
    },
  },
  {
    id: "cute",
    name: "Cute fantasy",
    appearance: {
      version: 1,
      skin: "#fde7d6",
      hair: "#e58fb5",
      eyes: "#8b5cf6",
      parts: {
        body: { id: "body_slim" },
        ears: { id: "ears_human" },
        face: { id: "face_round" },
        eyes: { id: "eyes_innocent" },
        eyebrows: { id: "brows_soft" },
        mouth: { id: "mouth_laugh" },
        hair: { id: "hair_twintails" },
        hairAccessory: { id: "hairacc_ribbon", colors: { primary: "#f2efe8", trim: "#d4af37" } },
        top: { id: "top_blouse", colors: { primary: "#f2efe8", secondary: "#6b3fa0", trim: "#d4af37" } },
        bottom: { id: "bottom_ruffle", colors: { primary: "#6b3fa0", secondary: "#c9a0dc", trim: "#f2efe8" } },
        shoes: { id: "shoes_maryjane", colors: { primary: "#6b3fa0", secondary: "#f2efe8", trim: "#d4af37" } },
        animalEars: { id: "animalears_cat", colors: { secondary: "#f2efe8" } },
      },
    },
  },
  {
    id: "adventurer",
    name: "Adventurer",
    appearance: {
      version: 1,
      skin: "#c68660",
      hair: "#6f4a30",
      eyes: "#3f9a6a",
      parts: {
        body: { id: "body_average" },
        ears: { id: "ears_human" },
        face: { id: "face_soft" },
        markings: { id: "markings_freckles" },
        eyes: { id: "eyes_sharp" },
        eyebrows: { id: "brows_straight" },
        mouth: { id: "mouth_smirk" },
        hair: { id: "hair_ponytail" },
        top: { id: "top_tunic" },
        vest: { id: "vest_jerkin" },
        belt: { id: "belt_leather" },
        bottom: { id: "bottom_trousers", colors: { primary: "#6b4a32", secondary: "#3b2a22" } },
        gloves: { id: "gloves_fingerless", colors: { primary: "#3b2a22", trim: "#b87333" } },
        shoes: { id: "shoes_ankle" },
        weapon: { id: "weapon_dagger" },
      },
    },
  },
  {
    id: "mage",
    name: "Mage",
    appearance: {
      version: 1,
      skin: "#f3c9a8",
      hair: "#f1ece2",
      eyes: "#8b5cf6",
      parts: {
        body: { id: "body_slim" },
        ears: { id: "ears_long_elf" },
        face: { id: "face_sharp" },
        markings: { id: "markings_arcane", colors: { primary: "#c9a0dc" } },
        eyes: { id: "eyes_arcane" },
        eyebrows: { id: "brows_elegant" },
        mouth: { id: "mouth_neutral" },
        hair: { id: "hair_hime" },
        dress: { id: "dress_robe" },
        necklace: { id: "necklace_pendant" },
        hat: { id: "hat_mage" },
        weapon: { id: "weapon_staff" },
      },
    },
  },
  {
    id: "warrior",
    name: "Warrior",
    appearance: {
      version: 1,
      skin: "#9a6243",
      hair: "#b3262e",
      eyes: "#d4a017",
      parts: {
        body: { id: "body_broad" },
        ears: { id: "ears_human" },
        face: { id: "face_sharp" },
        eyes: { id: "eyes_sharp" },
        eyebrows: { id: "brows_furrowed" },
        mouth: { id: "mouth_fang" },
        hair: { id: "hair_tousled" },
        top: { id: "top_turtleneck", colors: { primary: "#2f3440" } },
        vest: { id: "vest_cuirass" },
        belt: { id: "belt_leather" },
        coat: { id: "coat_cloak", colors: { primary: "#8f1d2c", secondary: "#16141c", trim: "#d4af37" } },
        bottom: { id: "bottom_trousers", colors: { primary: "#3b2a22", secondary: "#16141c" } },
        gloves: { id: "gloves_gauntlet" },
        shoes: { id: "shoes_greaves" },
        hat: { id: "hat_headband", colors: { primary: "#8f1d2c", secondary: "#d4af37" } },
        weapon: { id: "weapon_longsword", colors: { primary: "#c9ccd6", secondary: "#3b2a22", trim: "#d4af37" } },
      },
    },
  },
  {
    id: "modern",
    name: "Modern",
    appearance: {
      version: 1,
      skin: "#e0a882",
      hair: "#e0584f",
      eyes: "#5a3b25",
      parts: {
        body: { id: "body_slim" },
        ears: { id: "ears_human" },
        face: { id: "face_soft" },
        eyes: { id: "eyes_sleepy" },
        eyebrows: { id: "brows_straight" },
        mouth: { id: "mouth_neutral" },
        hair: { id: "hair_wolf" },
        top: { id: "top_turtleneck", colors: { primary: "#f2efe8" } },
        coat: { id: "coat_jacket" },
        bottom: { id: "bottom_flared" },
        shoes: { id: "shoes_ankle", colors: { primary: "#16141c", secondary: "#16141c", trim: "#c9ccd6" } },
        glasses: { id: "glasses_cateye" },
        earrings: { id: "earrings_hoops", colors: { primary: "#c9ccd6" } },
      },
    },
  },
  {
    id: "mysterious",
    name: "Mysterious",
    appearance: {
      version: 1,
      skin: "#b9c7e6",
      hair: "#17141c",
      eyes: "#e8e8f0",
      parts: {
        body: { id: "body_average" },
        ears: { id: "ears_elf" },
        face: { id: "face_sharp" },
        eyes: { id: "eyes_feline" },
        eyebrows: { id: "brows_soft" },
        mouth: { id: "mouth_neutral" },
        hair: { id: "hair_sweep" },
        top: { id: "top_turtleneck", colors: { primary: "#16141c" } },
        bottom: { id: "bottom_trousers", colors: { primary: "#16141c", secondary: "#16141c" } },
        coat: { id: "coat_cloak", colors: { primary: "#16141c", secondary: "#2b7a8c", trim: "#c9ccd6" } },
        gloves: { id: "gloves_fingerless" },
        shoes: { id: "shoes_tall" },
        mask: { id: "mask_cloth" },
        hat: { id: "hat_hood", colors: { primary: "#16141c", secondary: "#2b7a8c" } },
        weapon: { id: "weapon_dagger" },
      },
    },
  },
]
